app = "ad-performance"
primary_region = 'cdg'
kill_signal = 'SIGINT'
kill_timeout = '10s'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  HOST = '0.0.0.0'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2
  processes = ['app']
  
  [http_service.checks]
    grace_period = '30s'
    interval = '15s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.health]
    grace_period = '30s'
    interval = '15s'
    method = 'get'
    path = '/health'
    port = 3000
    timeout = '5s'
    type = 'http'
